package android.dev.personalassistant.utils;

/**
 * Created by saurabh on 4/1/18.
 */

public interface Constants {
    public String EXPENSE_TAG_MAX_KEY ="EXPENSE_TAG_MAX_KEY";
    public String EXPENSE_TAG_KEYS="EXPENSE_TAG_KEYS";
    public String EXPENSED_ON_TAG_SHARED_PREFERENCE="EXPENSED_ON_TAG_SHARED_PREFERENCE";
    public String EXPENSED_FOR_TAG_SHARED_PREFERENCE="EXPENSED_FOR_TAG_SHARED_PREFERENCE";
    public String EXPENSED_SMS_FILTER_SHARED_PREFERENCE="EXPENSED_SMS_FILTER_SHARED_PREFERENCE";
    public String EXPENSED_SMS_FILTER_SHARED_PREFERENCE_KEY="EXPENSED_SMS_FILTER_SHARED_PREFERENCE_KEY";

    public String DOCUMENTS_TAG_SHARED_PREFERENCE="DOCUMENTS_TAG_SHARED_PREFERENCE";
    public String DOCUMENTS_TAG_MAX_KEY ="DOCUMENTS_TAG_MAX_KEY";
    public String DOCUMENTS_TAG_KEYS="DOCUMENTS_TAG_KEYS";
    public String DOCUMENTS_IMAGES="DOCUMENTS_IMAGES";

    public String DOCUMENTS_SELECTED_TAG_KEYS="DOCUMENTS_SELECTED_TAG_KEYS";
    public String DOCUMENTS_SELECTED_TAG_SHARED_PREFERENCE="DOCUMENTS_SELECTED_TAG_SHARED_PREFERENCE";

    public String SELECTED_TAG_KEY="SELECTED_TAG_KEY";
    public String SELECTED_TAG_KEYS="SELECTED_TAG_KEYS";

    public String SMS_KEYWORDS="SMS_KEYWORDS";
    public String SMS_KEYWORDS_SET="SMS_KEYWORDS_SET";

    public static final String DATABASE_NAME  ="PERSONAL_ASSISTANT_DB";

    public static final String dateFormat="dd-mm-yyyy";

    public static final int SMS_READ_PERMISSION=5;
}
